### ISSUE TITLE
Congressional generic ballot link update

### ISSUE THREAD

**Issue by albarrentine** [fivethirtyeight/data#100]
Hi @dmil: it looks like the [Congressional generic ballot data](
https://github.com/fivethirtyeight/data/tree/master/congress-generic-ballot) link on this repo points to the Trump approval rating data instead. Is there a link to the CSV behind https://projects.fivethirtyeight.com/congress-generic-ballot-polls/?

**Comment by dmil** [comment]
Thanks for your note. I've updated those to link to the generic ballot data:
https://github.com/fivethirtyeight/data/tree/master/congress-generic-ballot

**Comment by albarrentine** [comment]
Thanks much!
