### ISSUE TITLE
Include reference to Creative Commons in LICENSE.md

### ISSUE THREAD

**Issue by oxinabox** [fivethirtyeight/data#101]
The readme includes the text:

> We hope you'll use it to check our work and to create stories and visualizations of your own. The data is available under the Creative Commons Attribution 4.0 International License and the code is available under the MIT License. 

LICENSE.md only include reference to MIT.

When looking for the licensing information people (and scripts) tend to look at the LICENSE.md and assume all the info is there.

It looks like someone has already made the mistake of thinking everything was under MIT.
https://www.kaggle.com/fivethirtyeight/fivethirtyeight

**Comment by dmil** [comment]
Thanks! We've changed the LICENSE file and have updated the README to more explicitly state both.
