### ISSUE TITLE
Add dataset for population and race percentages by county

### ISSUE THREAD

**Issue by oscardssmith** [fivethirtyeight/data#102]
I have compiled the following spreadsheet, which I think would be a good fit for this data repository. All data comes from 2010 census figures, and it's advantage over said tables is that it doesn't require going through a 5000 line cross reference to figure out what each column means, and all figures are in the same sheet instead split across 20 different ones over 3 files.

I understand that this repository is meant for datasets featured in 538 articles, but it seems likely that this sort of data will be used in the future, and I can't think of a better repository for this to live in.

[Race % and Pop by County.xlsx](https://github.com/fivethirtyeight/data/files/1633968/Race.and.Pop.by.County.xlsx)

**Comment by dmil** [comment]
As you mentioned, this repo contains data and code behind stories and interactives at FiveThirtyEight, so I'm going to go ahead and close the issue for now. Thanks for the suggestion.

**Comment by klatta87** [comment]
This is a great resource Oscar. Maybe depositing it on Kaggle would be a more appropriate repository. 
It would be great if a similarly formatted file was sourced from more recent American Community Survey data. Do you have an easy way to complie from that?

**Comment by oscardssmith** [comment]
no, this way made by decompiling census data and removing state info by hand
