### ISSUE TITLE
Is the shoot out data available?

### ISSUE THREAD

**Issue by bokmann** [fivethirtyeight/data#104]
I teach high school computer science with a match teacher who also teaches AP Stats. The raw 269,000 match preferences would be an awesome data set for us to play with.  Is that available? I only see your dataset which contains the reduction of that.

**Comment by walterhickey** [comment]
Which story in particular are you referring to? We should be able to get that for you.

**Comment by bokmann** [comment]
I’m referring to the candy voting dataset indicating which two candies went head to head and which one the person picked.  According to the article you also collected IP addresses so you could correlate votes from the same voters.

The IP addresses aren’t necessary, but might allow for some other analysis options I could give my students.  I could anonymize those into an integer ID and share it back with you if that would be useful.

**Comment by leekyosek** [comment]
Good

**Comment by nokrock** [comment]
Sex

**Comment by jayb** [comment]
Sorry, I don't think we have this data anymore unless @walterhickey still has a copy lying around.
