### ISSUE TITLE
nfl_elo incorrect playoff game dates

### ISSUE THREAD

**Issue by AustinNess** [fivethirtyeight/data#107]
I believe that the nfl_elo dataset may have the 2015 season wild card and division round playoff games on the wrong days:

![image](https://user-images.githubusercontent.com/5315807/36337361-9862979a-1362-11e8-8fc2-8f88e6c00d33.png)

According to wikipedia (and other sources that I followed up on), the wild-card games were on 1/9 and 1/10, with the divisional round on 1/16 and 1/17.

https://en.wikipedia.org/wiki/2015%E2%80%9316_NFL_playoffs#NFL_playoff_schedule

**Comment by jayb** [comment]
Thanks @AustinNess, this is fixed.
