### ISSUE TITLE
Replication details for subreddit-algebra

### ISSUE THREAD

**Issue by DGaffney** [fivethirtyeight/data#114]
Hello! I am interested in replicating the work presented in [Dissecting Trump’s Most Rabid Online Following](https://fivethirtyeight.com/features/dissecting-trumps-most-rabid-online-following/). After a review of the repository you've provided, it's unclear how to run the commands provided in data/processData.sql to produce the file you reference in the R file, "all_starting_2015_01_overlaps_top2200_no200_10com_allrank_mod_122716.csv". Can you provide either here in a response to this issue or in the README a more detailed explanation for the practical steps necessary to generate this CSV file? As provided right now, this repository does not contain enough information to replicate the work, although admittedly I have only used BigQuery a few times so may be missing something.

**Comment by spk8086** [comment]
this is a test post please ignore .................

**Comment by spk8086** [comment]
Test comment on a post

**Comment by Claybilly39** [comment]
r/imnew

**Comment by Claybilly39** [comment]
r/"all_starting_2015_01_overlaps_top2200_no200_10com_allrank_mod_122716.csv".

**Comment by poo2526** [comment]
https://github.com/issues?q=is%3Aopen+is%3Apr+mentions%3Apoo2526+archived%3Afalse+comments%3A%3E50+updated%3A%3C2018-02-12

**Comment by xyligan77** [comment]
Mm

**Comment by suraviafroze** [comment]
https://www.facebook.com/profile.php?id=100012675876061

**Comment by leekyosek** [comment]
Good

**Comment by RiskaOw** [comment]
accountkit

**Comment by DGaffney** [comment]
You think you can just close this!?
