### ISSUE TITLE
comma-survey does not contain data in article

### ISSUE THREAD

**Issue by Neato-Nick** [fivethirtyeight/data#120]
In the comma survey data set (https://github.com/fivethirtyeight/data/tree/master/comma-survey), the CSV with data does not contain the columns the story specifies. The story (https://fivethirtyeight.com/features/elitist-superfluous-or-popular-we-polled-americans-on-the-oxford-comma/) specifically shows a graph with how well people rated their own grammar, separated by if people used an Oxford comma. This graph cannot be recreated with the provided data.

**Comment by emline** [comment]
Looks like column with the question asking to rate own grammar is missing. If that was included, it looks like you can recreate the graph in the story. The second column that asks which sentence is preferred -- with or without Oxford comma -- appears to act as the preference filter in the chart.

**Comment by Neato-Nick** [comment]
Yep. I have been playing with the data and successfully made graphs showing
how much people cared about the comma based on whether or not they used it,
shown a correlation between caring about comma and caring about data, and a
couple other things. It's just an issue that the grammar *rating* column is
missing. Is this still housed somewhere, even though it's been almost 4
years?

**Comment by lyazidies** [comment]
Cómo obtener una visa para América y obtener una identificación

**Comment by bitbon57** [comment]
Cómo obtener una visa para América y obtener una identificación

**Comment by leekyosek** [comment]
Good

**Comment by Sattaya3979** [comment]
W

**Comment by jayb** [comment]
Sorry, but this data has been lost to time.
