### ISSUE TITLE
Any idea why this repo has been getting so much spam recently?

### ISSUE THREAD

**Issue by queuebit** [fivethirtyeight/data#173]
- Is there a way to stop it?
- Is this a problem with other big repos like https://github.com/rails/rails ?
- Am I just contributing to the spam by asking this question?

**Comment by dhwanlee** [comment]
test

**Comment by benbalter** [comment]
@ascheink I checked with our Platform Health team who took a closer look at the users that have been posting spam. The short answer is that it is likely the result of the repo being featured as part of Explore, as you suspected (spammers want their message to be seen so they target popular repositories). 

In the near term, if you or users report the content from the dropdown, we can get the user's account disabled, and we have some additional automated means of prevention that we're currently testing and hope to be able to roll out soon which should help. In the interim, please always feel free to contact GitHub support, as you have been, if we can ever be helpful. :smile:

**Comment by RZachLamberty** [comment]
Could this be a result of the [TalkPython 100 days of code course](https://training.talkpython.fm/courses/explore_100days_in_python/100-days-of-code-in-python)?

the authors reference this repo (or at least, [this transcript page indicates they do](https://training.talkpython.fm/courses/transcript/100-days-of-code-in-python/lecture/161402), I don't have direct access) as a primary source of `csv` information during days 37 - 39. The course materials were first posted to github on [Feb 1](https://github.com/talkpython/100daysofcode-with-python-course/commits/master/days/37-39-csv-data-analsys), which would put people taking the course linearly (Feb 1 + 37) in early March, when this started happening.
