### ISSUE TITLE
nfl_elo - missing 2018 data

### ISSUE THREAD

**Issue by numericOverflow** [fivethirtyeight/data#201]
Do you publish the ELO data from NFL predictions here on github each week?  

In the past it was possible to scrap predictions from the JS bundle, but 2018 seems to be very different format and (perhaps intentionally) difficult to get the elo matchup and predictions in a clean data format outside a webpage.

**Comment by jayb** [comment]
NFL Elo data can be found here: https://data.fivethirtyeight.com/

There is often extra data available for our interactives in `data.json` files, e.g.: https://projects.fivethirtyeight.com/2018-nfl-predictions/data.json
