### ISSUE TITLE
spi_matches

### ISSUE THREAD

**Issue by miloping** [fivethirtyeight/data#203]
Hi
May I know what is the difference between xG and nsXG?
Also, may I know exactly how is the projected score for each team calculated before the game?

Thanks!

**Comment by rvdmaazen** [comment]
If I understand correctly, xG is the number that represents the expected number of goals based on the shots taken by a team. The NSxG is the non-shot xG, i.e. the number of goals a team is expected to score based on their non-shooting actions such as passes and tackles. For more information about xG and NSxG as well as the calculation of projected scores check out [the methodology page for the Club Soccer Predictions](https://fivethirtyeight.com/methodology/how-our-club-soccer-predictions-work/).
