### ISSUE TITLE
Data for other presidents

### ISSUE THREAD

**Issue by chriskohoffman** [fivethirtyeight/data#209]
In regards to this data viz: https://projects.fivethirtyeight.com/trump-approval-ratings/

For the comparative lower section that compares Trump's approval ratings to the other Presidents, is there data for that as well? Thanks!

**Comment by dmil** [comment]
Thanks for your note. Unfortunately we haven't made that data available, however you can find a repository presidential approval polls over at the roper archive.

https://presidential.roper.center/

Hope that helps.
