### ISSUE TITLE
Democratic Primary Candidate Data Missing Column

### ISSUE THREAD

**Issue by shannongatta1** [fivethirtyeight/data#211]
For the dem_candidates.csv dataset, it says there should be a Gender column, but there is not one. Can you please provide?
![2018-12-01 14_39_17-data_primary-candidates-2018 at master fivethirtyeight_data](https://user-images.githubusercontent.com/19353228/49333633-021a6e00-f577-11e8-9c5d-f8e9ec118373.png)

**Comment by jayb** [comment]
I've removed the missing column from the README in https://github.com/fivethirtyeight/data/commit/90a87b2924dc2c584b9bf1926571063f0b1cbf56
