### ISSUE TITLE
Science Isn’t Broken

### ISSUE THREAD

**Issue by mGalarnyk** [fivethirtyeight/data#214]
Hey! 

I am curious if you have the data you used for the Science Isn't Broken article (https://fivethirtyeight.com/features/science-isnt-broken/). Particularly, the datasets you used for Hack Your Way To Scientific Glory figure. I know you mention where you got it, but do you have the "organized" form you used for it available? 

It really is an excellent article.

**Comment by jayb** [comment]
You may be able to find the data you're looking for in [this file](https://projects.fivethirtyeight.com/p-hacking/data.json).
