### ISSUE TITLE
data/partisan-lean/fivethirtyeight_partisan_lean_STATES.csv

### ISSUE THREAD

**Issue by adamfilinovich** [fivethirtyeight/data#215]
New Hampshire is given a partisan lean of R+33. For comparison, NH-1 is R+4 and NH-2 is D+1. If NH were actually 33 points more Republican than the nation, their state legislative election results would have had to have been 138 points more Republican (which is nonsensical).

**Comment by BeingofUniverse** [comment]
The only thing that makes sense to me is that it's a typo, instead of being R+3, they typed R+33.

**Comment by adamfilinovich** [comment]
> The only thing that makes sense to me is that it's a typo, instead of being R+3, they typed R+33.

That's probably it. It'd be nice is they gave us the state legislative elections data they have so it'd be easier to verify.

**Comment by juruwolfe** [comment]
Sorry about that, it was indeed a typo. It should be R+2. That's now fixed
