### ISSUE TITLE
Individual match predictions based on SPI

### ISSUE THREAD

**Issue by albertovth** [fivethirtyeight/data#216]
Check out this way of predicting individual matches: https://github.com/albertovth/postulated-reality/blob/master/StatFoot.py , based on your latest stats.
It was just meant as a data science exercise, which started as an Excel-VBA workbook, and that I later moved to Python. I am well aware that I could achieve the same result, while saving several lines of code... I also know that your model takes into consideration several other factors, to make match forecasts in very particular conditions. The way that I have set up things, only renders forecasts for matches in average conditions.
But I think it's fun to use this to make up own match-ups, also between national teams and clubs. I appreciate comments and feedback.

**Comment by jayb** [comment]
Cool!

**Comment by SoccerCashUK** [comment]
Hi maybe you could do the same for Club Soccer Predictions from FiveThirtyEight

James

**Comment by shivekbittu** [comment]
Why am I getting all these mails pls I w at to get rid of us.
