### ISSUE TITLE
Under "Club Soccer Predictions" in File "spi_matches.csv" Results Data has not updated since 1/30/2019

### ISSUE THREAD

**Issue by sal037** [fivethirtyeight/data#219]
In file "spi_matches.csv" The fields 

score1 | score2 | xg1 | xg2 | nsxg1 | nsxg2 | adj_score1 | adj_score2

have not updated with results from completed games beginning on 1/30/2019 with Athens vs. Levadiakos. I have downloaded on 2/5/19 and 2/8/19.

Thanks!

**Comment by sal037** [comment]
seems to only occur in the Zip File of all data, not in the individual spi_matches.csv file if downloaded alone from the link. Maybe the zip is not getting updated...

**Comment by sal037** [comment]
Closed it mistakenly

**Comment by dmil** [comment]
Thanks for your note. There was a technical issue on our end. This should be fixed now.
