### ISSUE TITLE
Oscars data?

### ISSUE THREAD

**Issue by nickresnick** [fivethirtyeight/data#221]
Any chance you could upload the oscars data you've used in the past? or the script that was used to generate it?

**Comment by cristianounix** [comment]
@nickresnick do you know what the columns are in this dataset ?

**Comment by nickresnick** [comment]
@cristianounix no idea. I just haven't come across a good oscars dataset and given 538's predictions in the past, thought maybe they'd have something stored away.

**Comment by makeyourownmaker** [comment]
There is a similar data set from [Iain Pardoe](https://iainpardoe.com/) available here:
https://github.com/tjmahr/GelmanHill/blob/master/datasets/academy.awards/

Data is available up to 2006.  

There is a related article: 
[Applying discrete choice models to predict Academy
Award winners](https://iainpardoe.com/refereed/08jrssa/oscars.pdf)

Hope this helps.
