### ISSUE TITLE
Searching for data used in specific articles

### ISSUE THREAD

**Issue by SimpleConjugate** [fivethirtyeight/data#225]
Do the maintainers have any suggestions for finding out if data in a particular article is accessible through here? I've looked through the [index](https://github.com/fivethirtyeight/data/blob/master/index.csv) for the [article of interest](https://fivethirtyeight.com/features/the-5-key-constituencies-of-the-2020-democratic-primary/?ex_cid=story-twitter#fn-2) and didn't see it.

**Comment by dmil** [comment]
Thanks for your note. All new datasets and their associated articles appear in that `index.csv` file and are also searchable at https://data.fivethirtyeight.com

Articles that have associated data should also have a link under the byline as shown below.
https://fivethirtyeight.com/features/how-the-citizenship-question-could-break-the-census/

<img width="632" alt="image" src="https://user-images.githubusercontent.com/468544/56746229-c9f41180-6749-11e9-8bea-1ce7448dcdb6.png">

Hope that helps!
