### ISSUE TITLE
Nutrition Studies FFQ

### ISSUE THREAD

**Issue by kgryte** [fivethirtyeight/data#232]
Two questions related to the nutrition studies FFQ [dataset](https://github.com/fivethirtyeight/data/tree/8af9e5b00b11fa495f5ca2dc5affb08a7a9f1350/nutrition-studies):

1. Would it be possible to include the administered FFQ (i.e., the questions which readers were asked to answer)?

2. Does a guide exist which explains the meaning of the dataset fields? Some are self-explanatory, such as, e.g., the frequency of eating fish `fishfreq`, but others are less so, such as, e.g., `sup_ca`.

Thanks!

**Comment by kgryte** [comment]
And also, seems as though some of the dataset fields are computed and/or aggregated. Would it be possible to also share the script used to compute the computed and aggregated fields?

**Comment by jayb** [comment]
Apologies, but we're unable to find the administered survey.
