### ISSUE TITLE
NBA game level forecasts don't include RAPTOR projections

### ISSUE THREAD

**Issue by actionpark** [fivethirtyeight/data#239]
In the CSV of your NBA forecasts it appears that it is still exporting a CARMELO projection. I thought that maybe it was just the header that needed to be updated but the first row, has Toronto with a 68% chance over the Pelicans and the RAPTOR projection on your site has them with a 70% chance.

https://github.com/fivethirtyeight/data/tree/master/nba-forecasts

**Comment by bradcenter** [comment]
I see Raptor win probability in column U and V

**Comment by jayb** [comment]
These are available in the raptor* columns.
