### ISSUE TITLE
Line endings are CR instead of LF or CR/LF

### ISSUE THREAD

**Issue by xnp** [fivethirtyeight/data#24]
Hello!

First of all, thanks for posting the data to the stories making it easier to follow the described methodology in each article. But, please, could you upload the csv files with correct line endings? As of now, most of the CSV files have CR line endings, instead of the more "canonical" LF or CR/LF. The following articles from StackOverflow provide some guidelines:

http://stackoverflow.com/questions/2332349/best-practices-for-cross-platform-git-config/
http://stackoverflow.com/questions/10491564/git-and-cr-vs-lf-but-not-crlf

Thanks!

**Comment by flipstewart** [comment]
Opened https://github.com/fivethirtyeight/data/pull/56 in case this is desired!

**Comment by dmil** [comment]
Thanks for the suggestion, I think we'll stick with the GitHub defaults for now. We can revisit if that is proving to be an issue for any users.
