### ISSUE TITLE
Raptor By Date?

### ISSUE THREAD

**Issue by ajkaill** [fivethirtyeight/data#240]
Is it possible to obtain the Raptor data broken down by date up until this point?

**Comment by ba31150** [comment]
yes

‫‪ajkaill‬‏ <‪notifications@github.com‬‏> در تاریخ شنبه ۹ نوامبر ۲۰۱۹ ساعت
۲۰:۳۷ نوشت:‬

**Comment by ajkaill** [comment]
Where? I only see them by Year and current.

**Comment by jayb** [comment]
This is not something we currently publish.
