### ISSUE TITLE
Googledrive files in R?

### ISSUE THREAD

**Issue by HedvigS** [fivethirtyeight/data#242]
Just out of curiosity, some of the data here is stored at google drive or somewhere else instead of here at GitHub.

- [https://docs.google.com/spreadsheets/d/e/2PACX-1vS15V8lYPUc_OH4OBss6d8NPGRnCH1lAlBBY4FYWcK6cm6iVM8dXE_4KMFOUybRe-cVvDg7ap46FPig/pub?gid=39569490&single=true&output=csv&/impeachment-polls.csv](https://docs.google.com/spreadsheets/d/e/2PACX-1vS15V8lYPUc_OH4OBss6d8NPGRnCH1lAlBBY4FYWcK6cm6iVM8dXE_4KMFOUybRe-cVvDg7ap46FPig/pub?gid=39569490&single=true&output=csv&/impeachment-polls.csv)
- [https://projects.fivethirtyeight.com/nba-model/2020/latest_RAPTOR_by_team.csv](https://projects.fivethirtyeight.com/nba-model/2020/latest_RAPTOR_by_team.csv)

Seems a bit cumbersome, but I'm sure there's in-house reasons for this that have to do with particular writers and analysts working in a particular workflow. Just out of curiosity, are you using the tidyverse googledrive package for the google stuff?

**Comment by jayb** [comment]
The dependency on Google Drive was removed in https://github.com/fivethirtyeight/data/commit/2414091fd8293a4f2848be4ab3b909408ea0f2b9.

The files hosted on `projects.fivethirtyeight.com` update often, so rather than make a lot of commits here, we link to them.
