### ISSUE TITLE
chess-transfers data doesn't contain info for all graphics

### ISSUE THREAD

**Issue by AmeliaMN** [fivethirtyeight/data#249]
The [chess-transfers](https://github.com/fivethirtyeight/data/tree/master/chess-transfers) dataset does not contain the information needed to make the first graphic in [American Chess is Great Again](https://fivethirtyeight.com/features/american-chess-is-great-again/), titled The Rise of the Trinity.

**Comment by jayb** [comment]
That dataset isn't included in this respository, but looks like it's available [here](http://ratings.fide.com/download.phtml).
