### ISSUE TITLE
How do you download the csv file

### ISSUE THREAD

**Issue by OscarAgbor** [fivethirtyeight/data#251]
Hi there,

Sorry for this but I am new to github and was redirected to this page for the college majors csv file. I am struggling to find the download button. I am trying to explore the data using pandas.

Kind regards and stay safe

Oscar

**Comment by dmil** [comment]
Greetings! Please check out our much easier to use data webpage: https://data.fivethirtyeight.com/

**Comment by dmil** [comment]
You can download all the same datasets there with one click!
