### ISSUE TITLE
Greece Super League games out of date

### ISSUE THREAD

**Issue by gobbedy** [fivethirtyeight/data#254]
Hello, There are several Greece Super League games coming up in the following days. Eg 3 games on July 15, 2020:
https://ca.soccerway.com/national/greece/super-league/20192020/championship-round/r53558/

But these are not shown on 538:
https://projects.fivethirtyeight.com/soccer-predictions/super-league-greece/

**Comment by jayb** [comment]
Thanks, this is fixed.
