### ISSUE TITLE
2020 General Election Results

### ISSUE THREAD

**Issue by mvastola** [fivethirtyeight/data#266]
Can you provide any insight into how (if at all) data sources will be updated as election results roll in on Nov 3rd? 

For instance, in the [presidential toplines](https://projects.fivethirtyeight.com/2020-general-data/presidential_national_toplines_2020.csv) will the [fields](https://github.com/fivethirtyeight/data/tree/master/election-forecasts-2020#presidential-forecast) `ecwin_inc` and `ecwin_chal` (or some other value) be updated to reflect probabilities that take into account exit polls and/or precinct data as it comes in?

And/or will those (or other) fields change to `1` or `0` as states are called? If so, what source (i.e. authority) will be relied on to determine if a state can be called?

Thanks a lot for providing this data!

PS: If no such updates to the data will be made, can you indicate when the final update to this data will be released? 

Thanks again!

**Comment by e-traudt** [comment]
States that cheat will be canceled by the New Republican House, if the
model fails to include that it is canceled now.

**Comment by mvastola** [comment]
> States that cheat will be canceled by the New Republican House, if the model fails to include that it is canceled now.
@e-traudt well that was decidedly unhelpful.

**Comment by tuchandra** [comment]
For the Democratic primaries, they froze their forecasts on the day of major primaries. See [South Carolina](https://fivethirtyeight.com/features/our-final-forecast-for-the-south-carolina-primary/), [Super Tuesday](https://fivethirtyeight.com/features/our-final-forecast-for-super-tuesday-shows-bidens-surge-and-lots-of-uncertainty/) and [a week after](https://fivethirtyeight.com/features/our-final-forecast-for-todays-primaries/), and more that I can't find. I imagine they'll do the same for the general, though I don't work there and can't speak for sure!
