### ISSUE TITLE
Codebook(s) for polling data?

### ISSUE THREAD

**Issue by adlainewson** [fivethirtyeight/data#272]
Are there codebooks available for the polling data (eg president_approval_polls.csv, president_polls.csv) that I'm not finding?

**Comment by l86-N78** [comment]
> Are there codebooks available for the polling data (eg president_approval_polls.csv, president_polls.csv) that I'm not finding?

**Comment by jayb** [comment]
We don't have codebooks available, but would be happy to answer any specific questions.
