### ISSUE TITLE
F1 Elo Ratings?

### ISSUE THREAD

**Issue by Eflores89** [fivethirtyeight/data#275]
Would it be possible to have data from this article? https://fivethirtyeight.com/features/formula-one-racing/

**Comment by queuebit** [comment]
Not sure if it helps but these two files seem to be used / requested from the page:

- https://projects.fivethirtyeight.com/f1-elo/drivers_clean.json
- https://projects.fivethirtyeight.com/f1-elo/drivers_final.json
