### ISSUE TITLE
How do you read this data 

### ISSUE THREAD

**Issue by jordan794** [fivethirtyeight/data#277]
Hey, does anyone know how to read this and what all the numbers mean?

https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-raptor/historical_RAPTOR_by_player.csv

**Comment by jordan794** [comment]
just figured it out

**Comment by dmil** [comment]
You can find more information on the README here:
https://github.com/fivethirtyeight/data/tree/master/nba-raptor
