### ISSUE TITLE
Please add year scrapped to readme

### ISSUE THREAD

**Issue by m3gan0** [fivethirtyeight/data#282]
Please add the year the data originates from to the readme in order to easily date it. Thank you!

**Comment by abitrolly** [comment]
Any ideas how to do this the smart way?

**Comment by m3gan0** [comment]
The readme currently reads:
The data comes from Marvel Wikia<http://marvel.wikia.com/Main_Page> and DC Wikia<http://dc.wikia.com/wiki/Main_Page>. Characters were scraped on August 24. Appearance counts were scraped on September 2. The month and year of the first issue each character appeared in was pulled on October 6.”

I would just add YYYY after the month to indicate when the data was pulled from the wikis. Ex:
“The data comes from Marvel Wikia<http://marvel.wikia.com/Main_Page> and DC Wikia<http://dc.wikia.com/wiki/Main_Page>. Characters were scraped on August 24, 2013. … Appearance counts were scraped on September 2, 2013. The month and year of the first issue each character appeared in was pulled on October 6, 2013.”

(I have no idea if 2013 is the right year BTW)
Thank you!
Megan (who is using this data set as an example in for a workshop)

**Comment by walterhickey** [comment]
hey! It was 2014. Here's the story in question: https://fivethirtyeight.com/features/women-in-comic-books/

**Comment by m3gan0** [comment]
I made a guess based on GitHub's "last updated 7 years ago" note :-)

**Comment by abitrolly** [comment]
So that's the README that needs a patch https://github.com/fivethirtyeight/data/tree/master/comic-characters

I thought the request is to adjust all READMEs to contain some kind of machine readable tag with the date.

**Comment by m3gan0** [comment]
Yes, sorry for the confusion. It's only the readme for the comic characters that needs a change.  Sorry for the confusion, I forgot that it was a subset of the fivethirtyeight repository.

**Comment by NeilPaine538** [comment]
OK, this should be fixed now!
