### ISSUE TITLE
Possible to fix line endings on comma survey?

### ISSUE THREAD

**Issue by pschloss** [fivethirtyeight/data#284]
I've been using the data from your [comma survey](https://raw.githubusercontent.com/fivethirtyeight/data/master/comma-survey/comma-survey.csv) for teaching R and some recent changes to the [R packages we use](https://github.com/r-lib/vroom/issues/360) make the line endings in your file problematic. Would it be possible for you to replace the line endings with `\r\n` or `\n` rather than the currently used `\r`?

**Comment by jayb** [comment]
Fixed by https://github.com/fivethirtyeight/data/pull/319
