### ISSUE TITLE
538 approval rating transparency 

### ISSUE THREAD

**Issue by blazespinnaker** [fivethirtyeight/data#289]
Can you publish the code you're using to calculate the 538 approval rating here - https://projects.fivethirtyeight.com/biden-approval-rating/

Given the national consequence of such a rating and the fact that its being traded on weekly with million dollar volume, I think it'd be ideal if 538 was transparent about how they're calculating these values.   

Right now, for example, because the results of a poll could move it when a model is recalculated - only insiders know the latest values until its updated on the website.

Code will allow anyone with access to polls the ability to precisely predict what the value will be before 538 has a chance to update it .  This will increase its nationwide credibility and ensure that nothing untoward is occurring.

cheers

**Comment by blazespinnaker** [comment]
Futhermore, I noticed that a poll was removed.  139395 

eg: 

https://web.archive.org/web/20210823082432/https://projects.fivethirtyeight.com/biden-approval-rating/polls.json

Why was it removed?  Did removing this poll have any impact on model recalculation?  I haven't done a full analysis via wayback on whether any other polls have been removed.  Can you explain the significance of this?

**Comment by blazespinnaker** [comment]
One more question - have you changed the model code or any of the parameters since the beginning of Biden's presidency?

**Comment by abitrolly** [comment]
The website looks like every president is cut down on after 200 days. Would be interesting to see real graph - how many days those guys are able to sustain before failing below 50%. Then linking that to how it connected to media coverage would be interesting as well.

**Comment by blazespinnaker** [comment]
Another detail which seems odd is that the weight / influence at the bottom of the page in the csv isn't the same as the weight published on the website.  When taking influence into account, they are actually not the same at all.

**Comment by blazespinnaker** [comment]
Another strange detail is that the correlation with Ras has increased significantly lately.  Was this due to a change in methdology?

![Ras/538](https://uploads.disquscdn.com/images/74feec86f0f68f6cf3943404145617935d1b0aeef4174be1eb4f4a7fc84fe2f4.png)

**Comment by jayb** [comment]
We don't publish the code behind our approval ratings, though perhaps one day we will.
