### ISSUE TITLE
Missing Players in Raptor Ranking 21-22

### ISSUE THREAD

**Issue by RJSSR** [fivethirtyeight/data#294]
Hi everyone!

There are some players missing for this season - I think it may be covid related.

List of Players:

Charlie Brown
Darren Collison
Donte DiVincenzo
Malcolm Hill
Matt Mooney
Quinndary Weatherspoon
Stanley Johnson
Tyler Hall

Hope you can fix it!

Thanks

**Comment by jayb** [comment]
Looks like these made it in there at some point.
