### ISSUE TITLE
Add ylab to ggplot with fivethirtyeight ggtheme

### ISSUE THREAD

**Issue by Montana** [fivethirtyeight/data#299]
For example, could I theoretically add:

```r
theme(axis.title = element_text()) + ylab('Something')
```
To my graph, but then I'll still get an `x axis` label. I'm thinking an alternative would be to use:

```r
theme(axis.title = element_text(), axis.title.x = element_blank()) + ylab('Something')
```
Any help is appreciated.

**Comment by jayb** [comment]
i believe that is answered [here](https://stackoverflow.com/questions/36181990/add-ylab-to-ggplot-with-fivethirtyeight-ggtheme).
