### ISSUE TITLE
Questionnaires (etc) used in data collection? 

### ISSUE THREAD

**Issue by hack-r** [fivethirtyeight/data#307]
Thanks so much for the code and data behind your research(!), but I am having trouble finding the associated questionnaires for all of the surveys/polls... are they available?

Any other artifacts such as descriptions of the data collection methodologies would also be highly useful and necessary for valid statistical analysis. Many thanks.

**Comment by jayb** [comment]
If you're looking for specific surveys, let us know and we can try to track them down. Many of the old ones are likely lost though.

**Comment by hack-r** [comment]
It was a long time ago that I was looking at your data, but in general that would be highly valuable to retain and publish. Cheers!
