### ISSUE TITLE
Home team and away team errors in NFL Data

### ISSUE THREAD

**Issue by mpeven** [fivethirtyeight/data#309]
Incorrect games that I've noticed:

- 2010-10-31, Denver Broncos at San Francisco 49ers
- 2010-12-14, New York Giants at Minnesota Vikings
- 2011-10-23, Chicago Bears at Tampa Bay Buccaneers
- 2012-10-28, New England Patriots at St. Louis Rams
- 2013-09-29, Pittsburgh Steelers at Minnesota Vikings
- 2013-10-27, San Francisco 49ers at Jacksonville Jaguars
- 2014-09-28, Miami Dolphins at Oakland Raiders
- 2014-10-26, Detroit Lions at Atlanta Falcons
- 2014-11-09, Dallas Cowboys at Jacksonville Jaguars

**Comment by jayb** [comment]
It looks like these were all games played on neutral fields, so our team order may be different from yours.
