### ISSUE TITLE
starting qbs for nfl(this is a question, not an issue)

### ISSUE THREAD

**Issue by easella** [fivethirtyeight/data#315]
How on earth do you get the starting qb for every nfl game since 1920?! I am making an ncaa football elo rating system and I am  looking to implement starting quarterbacks. How would you do that for every single ncaa football game since 1869?!

**Comment by jayb** [comment]
We got the NFL starting quarterbacks data from https://www.sports-reference.com/ -- they have college football data as well, but probably not back to 1869.

**Comment by easella** [comment]
ok, thanks!

**Comment by easella** [comment]
but how do you do it?what's the code?
