### ISSUE TITLE
How your ncaa football elo rating system works(this is a question, not an issue)

### ISSUE THREAD

**Issue by easella** [fivethirtyeight/data#321]
Hello, I'm making my own elo rating system for ncaa football. How does yours work?

**Comment by jayb** [comment]
Hello, here are a few articles where you can read about our football Elo ratings work:

https://fivethirtyeight.com/methodology/how-our-college-football-playoff-predictions-work/
https://fivethirtyeight.com/features/introducing-nfl-elo-ratings/
https://fivethirtyeight.com/methodology/how-our-nfl-predictions-work/
