### ISSUE TITLE
Update 2016 Potential Candidates?

### ISSUE THREAD

**Issue by slarson** [fivethirtyeight/data#37]
Looks like there's [a new article](http://fivethirtyeight.com/datalab/romney-not-running-for-president/) updating the potential candidates but the [data set](https://github.com/fivethirtyeight/data/tree/master/potential-candidates) doesn't reflect the new updates.  This could be a lot of fun to have access to as it gets updated.

**Comment by dmil** [comment]
Data for the new post is up. Thanks!
https://github.com/fivethirtyeight/data/tree/master/potential-candidates

**Comment by slarson** [comment]
Thanks!
