### ISSUE TITLE
Calculations for diverse/segregated cities?

### ISSUE THREAD

**Issue by anyonecancode** [fivethirtyeight/data#43]
It'd be great to see the calculations for http://fivethirtyeight.com/features/the-most-diverse-cities-are-often-the-most-segregated/

Particularly for calculating the _integration-segregation index_ (and, I suppose by necessity, the the trend line the index is based off).  The diversity index calcs we can get from footnotes 5 and 6, and the data from, as the article notes, US Census tract data. This gives readers enough to calculate diversity indices for any community (eg smaller towns and suburbs), but not enough to create an integration index.

**Comment by nik045** [comment]
:+1:

**Comment by dmil** [comment]
Thanks for your interest. Unfortunately we won’t be adding new data on this story.
