### ISSUE TITLE
Transition matrix calculation in pew-religions 

### ISSUE THREAD

**Issue by mbeltagy** [fivethirtyeight/data#45]
In https://github.com/fivethirtyeight/data/tree/master/pew-religions it is not clear how the transition data was obtained. In the full pew report I could not find the anything at that level of detail.

**Comment by leah-lib** [comment]
I reached out to Pew directly to get the full table -- they had only some
of the religions' data in full in their report.

**Comment by mbeltagy** [comment]
Thank you. 
FYI... Just for fun implemented the same analysis in Julia:
http://nbviewer.ipython.org/gist/mbeltagy/59ebbfd3e1811fe0a3ec

**Comment by leah-lib** [comment]
Thanks for sharing!
