### ISSUE TITLE
Issues with data in the college-majors repo

### ISSUE THREAD

**Issue by rhiever** [fivethirtyeight/data#52]
Hi all,

I've been working with the data in the `college majors` repo over the weekend: https://github.com/fivethirtyeight/data/tree/master/college-majors

I think something went wrong during the data processing, since if you compare the gender-related data in `recent-grads.csv` and `women-stem.csv`, they don't match up. `recent-grads.csv` also indicates that 56% of all computer science majors are female, which is way off.

I'm looking into the data right now to try to find out what happened, but I'd appreciate a second look at this data set to make sure everything is in order.

Cheers,
Randy

**Comment by dmil** [comment]
Hello Randy,

Thanks for correcting the data. I've checked with Ben and accepted the changes.

Best,

Dhrumil
