### ISSUE TITLE
Movie boxoffice data

### ISSUE THREAD

**Issue by eamoncaddigan** [fivethirtyeight/data#61]
Any chance of data getting posted for this article? http://fivethirtyeight.com/datalab/scary-movies-are-the-best-investment-in-hollywood

I guess this is a... feature request?

**Comment by eamoncaddigan** [comment]
I guess OpusData probably won't let the numbers be shared. I won't be salty if this gets closed.

**Comment by dmil** [comment]
Thanks for your interest. Unfortunately we won’t be adding new data on this story.
