### ISSUE TITLE
2016 Election Forecast data feed

### ISSUE THREAD

**Issue by jjaquinta** [fivethirtyeight/data#72]
(Feature request rather than data issue.)
Will you have a data feed for the 2016 Election Forecasts that can be used in 3rd party apps?
I've been writing voice applications for the Amazon Echo, including "Tweet Poll" which used "IBM Insights for Twitter" for state-by-state sentiment analysis of candidates during the primary season.
I'm interested in writing an interface that surfaces the daily 538 forecast. I would love to know if there is going to be a data feed for that, and what Terms and Conditions would apply to it. (Or who to talk to about setting up an app specific feed.)

**Comment by MarHai** [comment]
+1

Some sort of data feed or API would be great to have. Any plans on that?

**Comment by PinkAmpersand** [comment]
+1

**Comment by Eflores89** [comment]
+1

**Comment by rdarin** [comment]
+1

Want to leave a note saying that I'm not interested in it for any commercial application at all, simply for playing with other ways to visualize the output. Would love to see this implemented for the community.

**Comment by johnrb68** [comment]
+1

**Comment by nigel327** [comment]
+1

**Comment by khyew** [comment]
FYI you can scrape http://projects.fivethirtyeight.com/2016-election-forecast/mobile-bar.html for the polls-only percentages. The response is gzip-encoded and looks like this:

```
    <body>
        <a href="http://projects.fivethirtyeight.com/election-2016/primary-forecast/?ex_cid=mobilebar&amp;v=1">
            <div id="promo" class="mobile-bar">
                <div data-url="http://projects.fivethirtyeight.com/2016-election-forecast/?ex_cid=mobilebar&amp;v=1" class="data-wrap js-data-wrap">
                    <h3 class="title">
                        Chance of winning<span></span>
                    </h3>
                    <p class="value-wrap">
                        Clinton<span class="value">81.4%</span>
                    </p>
                    <p class="value-wrap">
                        Trump<span class="value">18.6%</span>
                    </p>
                </div>
                <div class="cta">
                    <span class="caret">❯</span>
                </div>
            </div>
        </a>
        <script src="//projects.fivethirtyeight.com/2016-election-forecast/js/mobile-bar-promo.js?v=87b9f41dac2f9cfbaf6a5510fb0ace97"></script>
    </body>
```

**Comment by ascheink** [comment]
Hi everyone, you can grab most of the data in the forecast here:

http://projects.fivethirtyeight.com/2016-election-forecast/summary.json

Let me know if there is anything that's not in that file that would be useful, and we can look into adding it. We definitely encourage people to build new interfaces to our forecast. I highlighted a few of my favorites here:

https://twitter.com/ascheink/status/783393969111756800

Feel free to email me if you have any questions, or if you build something you'd like to share: andrei.scheinkman@fivethirtyeight.com.

**Comment by rpearl** [comment]
@ascheink is the prediction percentage over time--the data used to generate the "chances over time" chart for each state available as json?

**Comment by ascheink** [comment]
@rpearl http://projects.fivethirtyeight.com/2016-election-forecast/NY.json

**Comment by jasonborneman** [comment]
Is individual senate race poll/projection data available via json like the presidential data above, @ascheink ? Thanks.

**Comment by bycoffe** [comment]
@jasonborneman The senate data for each state is available at similar URLs:

http://projects.fivethirtyeight.com/2016-election-forecast/senate/US.json
http://projects.fivethirtyeight.com/2016-election-forecast/senate/NY.json

There is no summary.json file for the senate.

**Comment by jasonborneman** [comment]
Made a slackbot for 538 presidential and senate data.
https://github.com/jasonborneman/538slackbot

Need to likely put in better error handling and make the code safer around error conditions, but it works well enough. Using it in a slack channel some friends and I are using to chat politics. It may not be pretty but it works and figured i'd put it out there.
