### ISSUE TITLE
Polls Data up until now

### ISSUE THREAD

**Issue by dfernan** [fivethirtyeight/data#73]
Hi,  not really a data issue but more like a FR.

Could you share the data you use for building this model?
http://fivethirtyeight.com/features/a-users-guide-to-fivethirtyeights-2016-general-election-forecast/

It seems you share the polls rating but not the polls results for this year, am I right?

**Comment by bycoffe** [comment]
The polls are available here: http://projects.fivethirtyeight.com/general-model/president_general_polls_2016.csv
