### ISSUE TITLE
Suggestion on repo structure

### ISSUE THREAD

**Issue by adamsb6** [fivethirtyeight/data#8]
I see that you're grouping all data sets in one repo.  While there's some convenience to organizing things that way, I think it's going to make it more difficult for curious readers to sort through once you've published hundreds of data sets.  It would probably be better  in the long term to do one repo for each story or data set, and then link to that individual repo from the story.

Given that there are only three data sets posted so far, this will be easier to re-organize now than later.

**Comment by Noctem** [comment]
I had the same thought. And submodules, as @alecbrooks mentioned, would be a good way to have your cake and eat it too.

**Comment by HollowDJ09** [comment]
I think that it would be easier for people who are trying to sort through the repositories if they were organised in a way that is similar to that of the website where they are put into categories or sub modules and then organized by alphabetical order.
