### ISSUE TITLE
"Measuring the Effect of the Economy on Elections"

### ISSUE THREAD

**Issue by emildmello** [fivethirtyeight/data#87]
If I could access the dataset related to this article, I'd really appreciate it! Working on undergrad research pertinent to Mr. Silver's work. 

Link: https://fivethirtyeight.blogs.nytimes.com/2012/07/05/measuring-the-effect-of-the-economy-on-elections/

**Comment by dmil** [comment]
Thanks for your interest. Unfortunately we won’t be adding new data on this story.
