### ISSUE TITLE
Elo Code

### ISSUE THREAD

**Issue by rogerfitz** [fivethirtyeight/data#91]
Do you guys have any plans to publish your Elo code? Specifically NBA Elo https://github.com/fivethirtyeight/data/tree/master/nba-elo

**Comment by deckoff** [comment]
What about the code behind NBA players projected plus/minus? I would be happy if you publish that :)

**Comment by jayb** [comment]
We don't have plans to publish the code, but we've made more historical data available:

https://github.com/fivethirtyeight/data/tree/master/nba-carmelo
https://github.com/fivethirtyeight/data/tree/master/nfl-elo
https://github.com/fivethirtyeight/data/tree/master/mlb-elo
https://github.com/fivethirtyeight/data/tree/master/soccer-spi

**Comment by easella** [comment]
yeah that would be helpful
