### ISSUE TITLE
Trump approval ratings API or raw data endpoint?

### ISSUE THREAD

**Issue by Eflores89** [fivethirtyeight/data#94]
FR: Is there any endpoint to the raw data similar to this: https://github.com/fivethirtyeight/data/issues/72

But for the trump approval ratings? https://projects.fivethirtyeight.com/trump-approval-ratings/

Thanks

**Comment by rogerfitz** [comment]
I think these are all of them. Use inspect element and network tab to view interactive visualization data sources. 
https://projects.fivethirtyeight.com/trump-approval-ratings/historical-approval.json  
https://projects.fivethirtyeight.com/trump-approval-ratings/approval.json  
https://projects.fivethirtyeight.com/trump-approval-ratings/polls.json  
https://projects.fivethirtyeight.com/interactive-recirc/interactive-recirc.json

**Comment by Eflores89** [comment]
Genius!
