### ISSUE TITLE
Data for Global Club Soccer Rankings

### ISSUE THREAD

**Issue by danielkesner** [fivethirtyeight/data#95]
https://projects.fivethirtyeight.com/global-club-soccer-rankings/

Are there any plans to make this data available through Github or any other mechanism? I'm building an application that requires a ranked list of soccer clubs and would love to use your dataset. If this list of ranked teams could be uploaded as a .csv here that would be fantastic.

**Comment by idinwoodie** [comment]
@danielkesner I think that it very unlikely due to the fact that the global club soccer rankings is a highly dynamic data set, and a majority of data sets they provide are static.

**Comment by jayb** [comment]
@danielkesner @idinwoodie You can find an updating csv of our club rankings here: https://projects.fivethirtyeight.com/soccer-api/club/spi_global_rankings.csv

You can also find SPI ratings back to Aug. 2016 in this file: https://projects.fivethirtyeight.com/soccer-api/club/spi_matches.csv
