### ISSUE TITLE
Data Dictionary for the datasets

### ISSUE THREAD

**Issue by harishkashyap** [fivethirtyeight/data#97]
Hi @BenCasselman thanks for uploading these useful datasets. Can we also get a data dictionary explaining the columns. For example, in the grad_students dataset, the columns of Grad_employed and Grad_unemployed don't add upto Grad_total. So a dictionary would go a long way to help. Also how was the unemployment rate was computed?

**Comment by dmil** [comment]
Hello and thanks for your note. Unfortunately I don't think we'll be editing previously posted data, however this  is a great suggestion and we'll keep it in mind for datasets we post going forward. You can also find more information about each dataset in the README file inside each folder.
