### ISSUE TITLE
Soccer SPI data

### ISSUE THREAD

**Issue by sjspielman** [fivethirtyeight/data#99]
Dear 538 team, 

I am curious about the preparation of your soccer data, here: [https://github.com/fivethirtyeight/data/tree/master/soccer-spi](https://github.com/fivethirtyeight/data/tree/master/soccer-spi). There appears to be some missing data: there are 467 unique teams in the matches csv, but only 453 teams in the ranks csv. Is it possible to obtain a complete version of this dataset? Thanks in advance for your help!

Best, 
Stephanie

**Comment by jayb** [comment]
Hi @sjspielman,

The teams file includes all men's teams from leagues we're forecasting this season, to reflect the list on https://projects.fivethirtyeight.com/global-club-soccer-rankings/

Some of the missing teams are women's teams (e.g. Boston Breakers), or teams who were included in a forecast last season but not this season (e.g. Bastia). If you want ratings for those teams, you can grab them from their most recent match in the matches file.

Hope that helps,
Jay
